#!/bin/sh
set -eu

if [ -z "${ROOT_DIR}" ]; then
    echo "ROOT_DIR must be set"
    exit 1
fi
if [ -z "${APPNAME}" ]; then
    echo "APPNAME must be set"
    exit 1
fi

if [ -d "${ROOT_DIR}/build" ]; then
    rm -f "${ROOT_DIR}/build/${APPNAME}"*
fi
